In [3]:
import numpy as np

In [7]:
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [5]:
type(a)

numpy.ndarray

In [10]:
A=np.array([[1.1,2.9,3],[3,4,5]])
print(A)

[[1.1 2.9 3. ]
 [3.  4.  5. ]]


In [12]:
A=np.array([[1,2,3],[3,4,5]],dtype=complex)
print(A)


[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [13]:
import numpy as np
a=np.array([1.0,2.0,3.0])
print(a)#row vector

[1. 2. 3.]


In [16]:
import numpy as np
v=np.array([[1],[2],[3]])#column vector
print(v)

[[1]
 [2]
 [3]]


In [17]:
import numpy as np
A=np.array([1,3,5,7])
B=np.array([6,7,8,9])
C=A+B
print(C)

[ 7 10 13 16]


In [18]:
import numpy as np
A=np.array([[1],[2],[3]])
B=np.array([[6],[8],[9]])
C=A+B
print(C)

[[ 7]
 [10]
 [12]]


In [20]:
import numpy as np
A=np.array([[1,2,3],[5,6,7]])
B=np.array([[1,5,6],[8,9,4]])
C=A+B
print(C)


[[ 2  7  9]
 [13 15 11]]


In [22]:
import numpy as np
A=np.array([[1,2,3],[0,0,0]])
B=np.array([[1,2,3],[4,5,6]])
C=A+B
print(C)

[[2 4 6]
 [4 5 6]]


In [31]:
import numpy as np
A=np.array([[1],[2],[3]])
print(A.transpose())


[[1 2 3]]


In [32]:
np.shape(A)

(3, 1)

In [33]:
#SCalar multiplication of matrix
import numpy as np
V1=np.array([[4,3,2]])
c=2
print("The Vector V1=",V1)
print("The Vector c*V=",c*V1)

The Vector V1= [[4 3 2]]
The Vector c*V= [[8 6 4]]


In [39]:
import numpy as np
V=np.array([[3],[6],[9]])
print("The Vector A:",V)
VV=np.array([[1,2,3]])
print("\nThe Vector B:",VV)
pro=V.dot(VV)
print(pro)

The Vector A: [[3]
 [6]
 [9]]

The Vector B: [[1 2 3]]
[[ 3  6  9]
 [ 6 12 18]
 [ 9 18 27]]


In [36]:
np.shape(V)

(3,)

In [2]:
#Outer Product
import numpy as np
a=np.array([2,4,8,7,7])
b=np.array([2,3,1,7,8])
#outr product in both order
opab=np.outer(a,b)
opba=np.outer(b,a)
print("\n\n---A---\n",a)
print("\n\n---B---\n",b)
print("\n\nOuter Product as A.B",opab)
print("\n\nOuter Product as A.B",opba)



---A---
 [2 4 8 7 7]


---B---
 [2 3 1 7 8]


Outer Product as A.B [[ 4  6  2 14 16]
 [ 8 12  4 28 32]
 [16 24  8 56 64]
 [14 21  7 49 56]
 [14 21  7 49 56]]


Outer Product as A.B [[ 4  8 16 14 14]
 [ 6 12 24 21 21]
 [ 2  4  8  7  7]
 [14 28 56 49 49]
 [16 32 64 56 56]]


In [9]:
import numpy as np
A=np.array([[3,6,7],[5,-3,0]])#2*3
B=np.array([[1,1],[2,1],[3,-3]])#3*2
D=A.dot(B)#Matrix wise multiplication
print("D=",D)#dimension of D
print(np.shape(D))
P=np.array([[3,6,7],[5,-3,0]])
Q=np.array([[1,1,2],[2,1,4]])
R=P*Q#elemnts-wise multiplication
print("R=",R)#not matrix multiplications

D= [[ 36 -12]
 [ -1   2]]
(2, 2)
R= [[ 3  6 14]
 [10 -3  0]]


In [23]:
import numpy as np
A=np.array([[1],[2],[4]])
#B=np.array([[2],[5],[7]])
B=A.transpose()
C=np.inner(A,B)
print("C=",C)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [26]:
#Vector Multiplication
import numpy as np
V1=np.array([4,5,6,7])
V2=np.array([[4],[5],[6],[7]])
V3=V1.transpose()
R1=V1.dot(V2)
#R3=V1.dot(V3)
#print(R3)
print(type(R1))
print(R1)
R2=V1.dot(V1)
print(type(R2))
print(R2)

126
<class 'numpy.ndarray'>
[126]
<class 'numpy.int32'>
126


In [27]:
#Vector Multiplication
import numpy as np
V1=np.array([[4,5,6,7]])
print(V1.shape)
V2=np.array([[4],[5],[6],[7]])
print(V2.shape)
R1=V2.dot(V1)
print(type(R1))
print(R1)

(1, 4)
(4, 1)
<class 'numpy.ndarray'>
[[16 20 24 28]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]


In [28]:
#Matrix Vector Multipluactiom
import numpy as np
V1=np.array([[1,2,3],[2,3,5],[3,6,8],[2,4,3]])
V2=np.array([[2],[3],[4]])
print(V1.shape)
print(V2.shape)
R1=V1.dot(V2)
print(R1)

(4, 3)
(3, 1)
[[20]
 [33]
 [56]
 [28]]


In [34]:
#diagonal Matrix
import numpy as np
x=np.arange(9).reshape((3,3))
print(x)
print("x1=",np.diag(x))
print("x2=",np.diag(x,k=1))#upper 2*2 matrix  k represents diagonalabove main diagonal
print("x3=",np.diag(x,k=-1))#lower 2*2 matrix here k represent diagonal below main diagonal
y=np.diag(np.diag(x))#making diagonal matrix
print(y)
z=np.diag([5,6,7])
print(z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]
[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[5 0 0]
 [0 6 0]
 [0 0 7]]


In [37]:
#Identity Matrix Property(I^K=I)
import numpy as np
I=np.eye(4)
print("\n---I(4x4)----",I)
k=14
Ik=I
for i in range(14):
    Ik=I*Ik#or I.dot(Ik)
print("\n\n----Ik-----\n",Ik)


---I(4x4)---- [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


----Ik-----
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
#Identity Matrix Property(AI=A)
import numpy as np
I=np.eye(3)
print("----MatrixI----\n",I)
A=np.array([[2,3,4],[3,45,8],[4,8,78]])
print("----Matrix A---",A)
ai=np.matmul(A,I);
print("Identity Matrix Property I.A",ai)
if ai.all()==A.all():# to check whether all elements in both matrox
    print("AI=A")

----MatrixI----
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----Matrix A--- [[ 2  3  4]
 [ 3 45  8]
 [ 4  8 78]]
Identity Matrix Property I.A [[ 2.  3.  4.]
 [ 3. 45.  8.]
 [ 4.  8. 78.]]
AI=A


In [40]:
#Determinant Of matrix
import numpy as np
M=np.array([[2,3,4],[3,45,8],[4,8,78]])
print("----Matrix A---",M)
det_A=np.linalg.det(M)
print("The determinannt of matrix A:",det_A)
M=np.array([[2,3,4],[3,14,8],[14,8,7]])
print("\n\n----Matrix B-----\n",M)
det_B=np.linalg.det(M)
print("The determiannt of Matrix B:",det_B)


----Matrix A--- [[ 2  3  4]
 [ 3 45  8]
 [ 4  8 78]]
The determinannt of matrix A: 5661.9999999999945


----Matrix B-----
 [[ 2  3  4]
 [ 3 14  8]
 [14  8  7]]
The determiannt of Matrix B: -347.00000000000006


In [10]:
#Inverse Of Matrix in python
import numpy as np
M=np.zeros((6,6))
print("\n------MATRIX A------\n",M)
ai=np.linalg.inv(M)
print("\nInverse of MAtrix M as---",ai)


------MATRIX A------
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


LinAlgError: Singular matrix